### ISSUE TITLE
FIA-PRISM example (spatiotemporal raster join)

### ISSUE THREAD

**Issue by ethanwhite** [weecology/pydataweaver#33]
A common form of join we will want to do is one that joins data based on both geographic location and time. An example of this would be joining FIA data with PRISM data.

1. Combine FIA tables to yield a table that for each FIA plot and year it is sampled has data in the form of `year, latitude, longitude, ...`
2. Join this with the PRISM data.
    * Simple version: Join with Yearly PRISM data which is one raster for each year. This is available in the monthly section of the FTP site by selecting the files without the months. E.g., the last file in the list here: ftp://prism.nacse.org/monthly/ppt/2016/
    * Complex version: Join with the Monthly PRISM data which is one raster for each month in each year (the files with month numbers in the link above). Do a calculation across the monthly values to create a single value for each row in the FIA table. E.g., the maximum monthly precipitation for that year.

I'd definitely start with the simple version, but ultimately we'll want to be able to do the complex version because this will let us combine data with different sized time windows (e.g., to average over daily data from a raster to combine it with tabular data that only has one value per year).

**Comment by MarconiS** [comment]
An option I am following to make the _complex_ version is to download directly the point/surface data for the year (or time series) am interested in, and then aggregate using dplyr. Data can be automatically download using: (a)  gridded subset scripts if you want a raster region (https://github.com/ornldaac/gridded_subset_example_script), or (b) tabular form using the python library daymetpi (https://khufkens.github.io/daymetpy/)
